language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

script:
  - python src/main.py --server --terminal

notifications:
  email:
    on_success: always
    on_failure: always