language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

script:
  - python payload/rsa/encrypt.py
  - python payload/rsa/decrypt.py
  - python payload/rsa/key.py
  - python payload/rsa/rsa.py

  - python src/main.py

notifications:
  email:
    on_success: always
    on_failure: always